### ISSUE TITLE
Unable to find existing contract.

### ISSUE THREAD

**Issue by Alexunderlett** [paritytech/substrate-contracts-node#14]
When I add an existing contract in the contract tray of polkadot.js，
“the contract code for the deployment could not be found at the specified address”

**Comment by cmichi** [comment]
@Alexunderlett Can you provide more details?

A thing to notice is that when you start the node with `--tmp` the existing database is removed with each start of the node. Was this maybe already your issue?

**Comment by HCastano** [comment]
@Alexunderlett I'm gonna close this. If you're still having trouble feel free to re-open it!
