### ISSUE TITLE
Easier setup & update

### ISSUE THREAD

**Issue by wottpal** [paritytech/substrate-contracts-node#149]
It would be cool to have easier setup in place, other than just manually downloading a binary and moving it to `/usr/local/bin` (or storing it elsewhere) each time it updates. e.g. via homebrew or as a global npm package.

**Comment by smiasojed** [comment]
I think that the recommended procedure is to use:
`cargo install contracts-node`

the latest release: `cargo install contracts-node --version 0.39.0`
Please feel free to reopen if it does not solve your issue
