### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by wwrdumbaf** [paritytech/substrate-contracts-node#150]
Hey when I try to install this node I run 

`cargo install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git --force --locked`

I get '29 errors' and most of them look like this: 

type Call = Call;
      |     ^^^^^^^^^^^^^^^^^ not a member of trait `frame_system::Config`

  error[E0437]: type `Event` is not a member of trait `frame_system::Config`
     --> /Users/kk/.cargo/git/checkouts/substrate-contracts-node-cf7c16677784d274/8d76d04/runtime/src/lib.rs:187:2
      |
  187 |     type Event = Event;
      |     ^^^^^^^^^^^^^^^^^^^ not a member of trait `frame_system::Config`

  error[E0437]: type `Event` is not a member of trait `pallet_balances::Config`
     --> /Users/kk/.cargo/git/checkouts/substrate-contracts-node-cf7c16677784d274/8d76d04/runtime/src/lib.rs:251:2
      |
  251 |     type Event = Event;
      |     ^^^^^^^^^^^^^^^^^^^ not a member of trait `pallet_balances::Config`

I have tried multiple different versions of rust and different tags of the contracts-node and I can't seem to find a fit. I am running the most up to date rust toolchain and v0.20.0 of the contracts-node.

I am new to this plz go easy on me thanks

**Comment by cmichi** [comment]
Hi there!

> I am running the most up to date rust toolchain and v0.20.0 

Is that `stable` or `nightly`? Which operating system are you using?

Have you tried `cargo clean` in the folder?

Until this is resolved: Can you use the binary directly on your operating system? You can download it here: https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.20.0.

**Comment by abing258** [comment]
> 你好呀！
> 
> > 我正在运行最新的 rust 工具链和 v0.20.0
> 
> 那是`stable`还是`nightly`？您使用的是哪个操作系统？
> 
> 你`cargo clean`在文件夹里试过吗？
> 
> 在解决此问题之前：您可以直接在您的操作系统上使用二进制文件吗？你可以在这里下载：[https](https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.20.0) ://github.com/paritytech/substrate-contracts-node/releases/tag/v0.20.0 。

我也碰到同样的问题，但是我的二进制文件是可以运行的。rustc 1.64.0-nightly (848090dcd 2022-07-22)

**Comment by gitgitcode** [comment]
same error 
- rustc 1.64.0 (a55dd71d5 2022-09-19)
- Apple M1 12.5
- rustup 1.25.1 (bb60b1e89 2022-07-12)
- 
```

 error[E0437]: type `Call` is not a member of trait `frame_system::Config`
     -->  /.cargo/git/checkouts/substrate-contracts-node-cf7c16677784d274/8d76d04/runtime/src/lib.rs:173:2
......

 Building [=======================> ] 939/949: librocksdb-sys(build)
error: failed to compile `contracts-node v0.20.0 (https://github.com/paritytech/substrate-contracts-node.git?tag=v0.20.0#8d76d04f)`, intermediate artifacts can be found at `/var/folders/td/bs9n_nsj4vv2vdv16t_psxwm0000gn/T/cargo-install9PDOeJ` 
```

**Comment by TomaszWaszczyk** [comment]
Look at here: https://stackoverflow.com/questions/66583720/some-error-failed-to-run-custom-build-command-for-librocksdb-sys-v6-11-4

Probably you need to execute: `sudo apt install clang`
