### ISSUE TITLE
Provide a feature to specify block finality time

### ISSUE THREAD

**Issue by DoubleOTheven** [paritytech/substrate-contracts-node#160]
instant finality makes front end development difficult, and unrealistic. It would be great to be able to simulate the various states of a transaction `in block`, `finalized`, etc

**Comment by wottpal** [comment]
> I think we should just move to a very short block time (<< 1s) instead of having instant finality.

Would be perfectly fine from my side (if that actually solves the problem above, but I guess) :)

**Comment by athei** [comment]
The main concern from @cmichi was that it will slow down e2e tests against the node. But if we make the block time really short it should be no problem. I think we can go as low as we want since no networking is involved.

wdyt @cmichi ?

**Comment by cmichi** [comment]
We could also add a flag `--instant` for e2e tests and default to a block time of e.g. 0.5 sec.

**Comment by cmichi** [comment]
@PierreOssun Do you have any thoughts here? And more important: would you by chance be up for implementing it 😊? Asking because you were so kind to do the original PR for instant finality.

**Comment by wottpal** [comment]
Just pushing this up once again, as I stumble across issues everywhere due to the instant finality nature of `substrate-contracts-node`. 

For example I wanted to index my local node with Subsquid, and when starting its archive (https://github.com/subsquid/substrate-archive-setup) it says `chain height: 0`. But when connecting to a different local node (i.e. `aleph-node`) it works instantly. Already spoke to one of their devs who also assumes this is related to instant block finality.

**Comment by shunsukew** [comment]
@cmichi How about this approach?
If this seems good, I'll continue to make PR in the Substrate repo.
spawning new task which subscribes block import stream, and finalizes it after waiting for configured delay time.
https://github.com/shunsukew/substrate/pull/1/files

**Comment by shunsukew** [comment]
@wottpal 
I'm preparing PR in Substrate, but you can use this swanky-node's branch if you wish https://github.com/AstarNetwork/swanky-node/pull/61

**Comment by shunsukew** [comment]
Released v1.6.0 with delayed finalize feature
https://github.com/AstarNetwork/swanky-node/releases/tag/v1.6.0

**Comment by wottpal** [comment]
Thanks @shunsukew, I just tried it, and it's working smoothly 👌🥳 

It fixes both problems mentioned above:
* `polkadot.js` extrinsic status now gets finalized,
* local subsquid archive node is working as expected and recognizes block height (FYI @RaekwonIII).

Would love to see this in `substrate-contracts-node`, too @cmichi @athei 🤩

**Comment by shunsukew** [comment]
That's great to hear!

**Comment by athei** [comment]
> Would love to see this in substrate-contracts-node, too @cmichi @athei 🤩

PRs welcome :)

**Comment by niklasp** [comment]
I am running into this issue and want regular frequency blocks for frontend development. The current version does not allow me to add papi descriptors from a running node
