### ISSUE TITLE
Error "OutOfGas" occurred when calling contracts with the newest version

### ISSUE THREAD

**Issue by virgil2019** [paritytech/substrate-contracts-node#164]
# Environment
- OS: WSL Ubuntu 20.04
- Ink toolkit: 2.0.0.beta
- Ink sdk: 4.0.0.beta
- Node: substrate-contracts-node 0.22.1-75efc0b836f

# Contracts
Here I use the example code `ERC20`.

# Operations
## Build
```
cargo contract build
```

## Deploy
Deploy the contract on the polkadot.js/apps

## Call
Call the method `totalSupply`, `transfer`.

## Result
Call failed with errer "Out Of Gas"

4.0.0.alpha.3, 2.0.0.alpha.3 and node 0.20 worked well for me

**Comment by athei** [comment]
polkadot.js/apps is incompatible with newer versions of this node. Use either `cargo contract` or [ContractsUI](https://contracts-ui.substrate.io/).

Reason is the switch to WeightsV2.
