### ISSUE TITLE
Balance Getting Reserved while deploying Contract?

### ISSUE THREAD

**Issue by Amit22antier** [paritytech/substrate-contracts-node#171]
i am using substrate i tried deploying **wasm smart-contract using pallet-contracts** in which i can see some balance is getting reserved from the account which is used to deploy the contract `**in substrate 195,909,000,000,000,000 is getting reserved while contract deployment`**  as i can see in **Substrate-contract-node** the reserved  balance is` **463,145,000,000** ` which is very less. 
How can i set it to minimum balance to be reserved ? but i don't know exactly where to make changes in my code???

**Comment by athei** [comment]
Deposits are configured here: https://github.com/paritytech/substrate-contracts-node/blob/430873a4fbed3da99cae973d2095c1ce34985311/runtime/src/lib.rs#L342-L343

Please consider asking questions on the substrate stack exchange rather than opening an issue.
