### ISSUE TITLE
nightly toolchain still required

### ISSUE THREAD

**Issue by wottpal** [paritytech/substrate-contracts-node#173]
As far as I'm aware, `cargo-contract` doesn't require the nightly toolchain anymore to be installed since v2 but instead the stable one. Though, `contracts-node` still requires it, which results in the need to install both toolchains when setting things up. Is this still really required or is this error only a leftover?

![Screen_Shot_2023-02-23_at_17 36 30](https://user-images.githubusercontent.com/3930150/221127827-e651d38d-297c-4357-812d-0891fd06d69a.png)

**Comment by athei** [comment]
Substrate [still requires](https://github.com/paritytech/substrate/issues/1252) `nightly`. It is the `wasm-builder` crate that enforces this rule.
