### ISSUE TITLE
Error: Service(Client(VersionInvalid("cannot deserialize module: UnknownOpcode(192)")))

### ISSUE THREAD

**Issue by scab24** [paritytech/substrate-contracts-node#178]
# When I try to run "substrate-contracts-node --dev" I get this error:

 ## WARN main wasm-runtime: Cannot create a runtime error=Other("cannot deserialize module: UnknownOpcode(192)")
## Error: Service(Client(VersionInvalid("cannot deserialize module: UnknownOpcode(192)"))

I'm use MAC M1
### substrate-contracts-node 0.24.0-fe448511262

====
rustup +nightly show
Default host: aarch64-apple-darwin
rustup home:  /Users/secoalba/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2023-03-14-aarch64-apple-darwin
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.68.2 (9eb3afe9e 2023-03-27)

Default host: aarch64-apple-darwin
rustup home:  /Users/secoalba/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2023-03-14-aarch64-apple-darwin
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-aarch64-apple-darwin (overridden by +toolchain on the command line)
rustc 1.70.0-nightly (700938c07 2023-04-04)

**Comment by klimenkoOleg** [comment]
This is due to version incombatibility.

Create in the root of the project file 'rust-toolchain.toml' and place the following content:
`[toolchain]
channel = "nightly-2023-01-01"
components = [ "rustfmt" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
`
This worked for me, I also use Mac with M1 CPU.

**Comment by wottpal** [comment]
For everyone stumbling across this one, either fix it by using the [provided binary](https://github.com/paritytech/substrate-contracts-node/releases) instead. Or install `substrate-contracts-node` again with an older fixed nightly build of the rust toolchain like:

```
rustup install nightly-2023-02-07-aarch64-apple-darwin
rustup target add wasm32-unknown-unknown --toolchain nightly-2023-02-07-aarch64-apple-darwin
cargo +nightly-2023-02-07 install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git --force --locked
```

**Comment by scab24** [comment]
Thank you very much, it is working properly, I appreciate it very much.

**Comment by vineshtk** [comment]
> For everyone stumbling across this one, either fix it by using the [provided binary](https://github.com/paritytech/substrate-contracts-node/releases) instead, or install `substrate-contracts-node` again with an older fixed nightly build of the rust toolchain like:
> 
> ```
> rustup install nightly-2023-02-07-aarch64-apple-darwin
> rustup target add wasm32-unknown-unknown --toolchain nightly-2023-02-07-aarch64-apple-darwin
> cargo +nightly-2023-02-07 install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git --force --locked
> ```

Thanks for the help, this works .

**Comment by athei** [comment]
Should be fixed with the latest master.
