### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate-contracts-node#203]
Now that there are up to date crates released to crates.io, we should use those dependencies, and also publish `substrate-contracts-node` there.

We would need https://github.com/Brushfam/pallet-assets-chain-extension to be published to crates.io, or could copy it into this repository.

**Comment by deuszx** [comment]
Or we can remove the extension entirely from the `subtrate-contracts-node`. It seems like a random thing. Do we even know for sure that it's working correctly? There's no CI in the repo or tests.

**Comment by ascjones** [comment]
#204

**Comment by ascjones** [comment]
https://crates.io/crates/contracts-node
