### ISSUE TITLE
Storage Limit issues

### ISSUE THREAD

**Issue by forgetso** [paritytech/substrate-contracts-node#23]
This node seems to not work with the recent changes surrounding storage limits.

When uploading contracts the following error is received:

`contracts.StorageDepositLimitExhausted(More storage was created than allowed by the storage deposit limit.)`

A normal substrate node started with `cargo run --release -- --dev --tmp -lerror,runtime::contracts=debug` works using the same configuration of polkadotjs and deploy script.

I have even upgraded the substrate contracts node to a recent substrate commit to see if that was the issue but it still fails on deployment.

https://github.com/prosopo-io/substrate-contracts-node/tree/storage_deposit_limit (Synced to https://github.com/paritytech/substrate/commit/7409589ab78e7cb508db873dd6384634d667b8f5)

I can create a PR for this if you like.

polkadot-js versions:

```
    "@polkadot/api": "7.2.1",
    "@polkadot/api-contract": "7.2.1",
    "@polkadot/types": "7.2.1",
    "@polkadot/keyring": "8.2.2",
    "@polkadot/util": "8.2.2",
    "@polkadot/wasm-crypto": "4.5.1",
    "@polkadot/util-crypto": "8.2.2",
```

**Comment by forgetso** [comment]
The issue seems to be the inconsistent default values assigned to `Alice` in the substrate-contracts-node versus substrate.

- In substrate the accounts are seeded with `1,000,000,000,000,000,000,000`.
- In substrate-contracts-node the accounts are seeded with `1,152,921,504,606,846,976 (1<<60)`.

Both scripts use the same deploy script which passes a value of `20000 UNIT` to the contract.

The substrate deploy succeeds whereas the substrate-contracts-node fails with `contracts.StorageDepositLimitExhausted`.

It doesn't seem to make any difference as I increase the sent value. It always fails with the same error. The highest value I tried was `2000000000000000 UNIT`

To reproduce, you can clone our [smart contract repo](https://github.com/prosopo-io/protocol) and run the deploy script with substrate-contracts-node built with default values of `1,000,000,000,000,000,000,000` and `1,152,921,504,606,846,976`.

```
git clone https://github.com/prosopo-io/protocol \
&& cd protocol \
&& yarn \
&& yarn build \
&& yarn redspot run scripts/deploy.ts
```

**However, there is a caveat** that we are using a slightly [modified version of ink](https://github.com/paritytech/ink/pull/1080) that allows for `SpreadAllocate` on `enum`. The contract will not build without this.

**Comment by athei** [comment]
Does the error also happen with the unmodified substrate node (the man if you just use `cargo run` in the substrate repo)?

**Comment by forgetso** [comment]
The error does not happen with the unmodified substrate repo. I've outlined what I've tested below.

| Package     | Balance | Result |
| ------------- | ------------- | ------------- |
| substrate |  `1,000,000,000,000,000,000,000` | succeeds |
| substrate |  `1<<60` | ??? |
| substrate contracts node | `1<<60` | fails |
| substrate contracts node | `1,000,000,000,000,000,000,000` | succeeds |

Clearly this could be further narrowed down by checking substrate with the initial balances as `1<<60`. I've not had time to check this out as currently trying to finish up work for a Web3 milestone.

**Comment by forgetso** [comment]
The confusion was caused by the differing initial balances for Alice etc. After this was taken into consideration, it turns out I can send a large enough initial deposit to my account by passing the number through `BN`, getting around the `StorageDepositLimitExhausted`.

e.g. send a large initial deposit to my testing account
`new BN("100000000000000000") // it's important that a string is passed`
