### ISSUE TITLE
branch protection

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/substrate-contracts-node#28]
Last week, while writing https://github.com/paritytech/substrate-contracts-node/pull/27 I accidentally pushed to upstream `main` while thinking it was my fork.

Then I rebased and force-pushed to undo my mistake.

As discussed with @cmichi , this issue is a reminder to set branch protections so we avoid dummies like myself screwing up the repo in the future.

**Comment by cmichi** [comment]
Thanks! I've applied the same branch protection rules as we have for `cargo-contract`.
