### ISSUE TITLE
Make block time configurable

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate-contracts-node#36]
@xgreenx came up with this idea.

We should look into making the block time here configurable for CI/testing purposes. In those environments most often only a standalone node is used anyway (so no consensus issues) and in the case of e.g. `ink-waterfall` the tests are often blocked waiting for the next block. 

https://github.com/paritytech/substrate-contracts-node/blob/82834b3dd11d43eb257a56e66cd6201dc22a7d5b/runtime/src/lib.rs#L107-L113

By decreasing this to a way smaller value the CI's which are using this node could be sped up significantly.

**Comment by HCastano** [comment]
Instead of doing this why not use manual seal/instant seal? That way blocks are produced when transactions are submitted to the node, regardless of the time

**Comment by gabriel-viviani** [comment]
I'm VERY new to blockchain world. I think if discussion goes in the using manual/instant seal it would be an advanced topic/implementation. Should I wait for you guys to discuss it or go ahead and trying to help with the configurable opt?!

**Comment by xgreenx** [comment]
> Instead of doing this why not use manual seal/instant seal? That way blocks are produced when transactions are submitted to the node, regardless of the time

Creating blocks on-demand after each transaction will be cool. But it requires changes from `substrate` and it maybe it's not easy to implement. But to have that feature(blocks on demand) configurable will be perfect for testing.

**Comment by cmichi** [comment]
I didn't know about manual seal/instant seal and skimmed https://github.com/paritytech/substrate/pull/4143/files quickly. It's a different consensus engine, so would require switching the engine altogether ‒ thus resulting in more complexity in this node. I'd like to keep it as simple as possible, making it easy to maintain and grasp for people looking how to integrate `pallet-contracts`.

So my preference would be to just make this variable configurable.

**Comment by HCastano** [comment]
I haven't looked at the manual seal stuff since it was merged, but I don't imagine it should be that hard to integrate it into a node. 

For development it makes a lot of sense to have it though. I say the extra complexity is worth is, especially since that's code that wouldn't change very often.

Not to put any pressure on you @gabriel-viviani, but maybe as a good starting point can you go through the [Substrate Seminar](https://www.youtube.com/watch?v=uhkV0jAcWDY) related to manual seal and see what's required to integrate it into a node?

**Comment by HCastano** [comment]
@gabriel-viviani Hey! Any updates here 😃?

**Comment by themartto** [comment]
so what now if I need to go back to the normal aura/grandpa block production?
