### ISSUE TITLE
cargo install contracts-node fails due to missing 'LengthToFee' in implementation

### ISSUE THREAD

**Issue by DukeCaesar** [paritytech/substrate-contracts-node#48]
When running command
`cargo install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git --force --locked`
Several errors show up.

First error says Cargo.lock could not be found for runtime.

There are several more errors at the end of the installing process:

`error[E0437]: type 'TransactionByteFee' not a member of trait 'pallet_transaction_payment::Config' `
in runtime/src/lib.rs:265:2.
`error [E0046]: not all trait items implemented, missing: 'LengthToFee'`

This is caused by the upstream breaking changes of Subtrate #10785 
[https://github.com/paritytech/substrate/pull/10785](url)

This change replace 
`type TransactionByteFee = TransactionByteFee;`
with
`type LengthToFee = IdentityFee<Balance>;`

This confirms that Cargo.lock somewhat fails to secure the installing of specific versions of some dependencies.

A workaround of this error is first to git clone the repo to local device.
`git clone https://github.com/paritytech/substrate-contracts-node.git`
then call:
`cargo install contracts-node –path substrate-contracts-node/node –force –locked`

**Comment by gilescope** [comment]
Agreed. I see the same. Master works.
