### ISSUE TITLE
can not connect to ws://127.0.0.1:9944 on latest substrate-contracts-node

### ISSUE THREAD

**Issue by JohnRioDefi** [paritytech/substrate-contracts-node#97]
Hello,

I just downloaded and built the latest substrate-contracts-node and run it using the command: 
`substrate-contracts-node --dev`
![image](https://user-images.githubusercontent.com/96169740/170081141-59881bea-a5df-46a1-aeae-21a74edb7217.png)

Then open this URL in the browser on the same machine:
https://paritytech.github.io/contracts-ui/#/?rpc=ws://127.0.0.1:9944

but it says can not connect to ws://127.0.0.1:9944 as following showed:
![image](https://user-images.githubusercontent.com/96169740/170080153-0b9c874c-efc4-44e9-a53c-79d1212353d2.png)

Could anyone help to solve this?
Thanks!

**Comment by peetzweg** [comment]
Looks to me like you are using quite the outdated version of the `substrate-contracts-node`. During initialization it prints `version 0.16.0`. By now we are at `version 0.24.0`. Can confirm 0.24.0 works fine with me. 

Can you upgrade to the new `susbtrate-contracts-node` and try it again?
You can download the prebuilt binary from the release section of the [`substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node) repo.

https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.24.0
